In [46]:
# Creating an array 
import numpy as np
import pandas as pd


In [47]:
np_version = np.__version__
pd_version = pd.__version__
print("NUmpy version:{numpy}".format(numpy = np_version))
print("Pandas version:{panda}".format(panda = pd_version))

NUmpy version:1.16.2
Pandas version:0.24.2


## Creating an array
A list of numbers can be passed to the following array function to create a NumPy array object:

In [14]:
n_array = np.array([
[0,1,2,3],
[12,4,6,9],
[8,4,6,77]
]
)
print("dimension:",n_array.ndim)
print("Shape:",n_array.shape)
print("Size:",n_array.size)
print("Data type:",n_array.dtype.name)

dimension: 2
Shape: (3, 4)
Size: 12
Data type: int32


# Mathematical operations 
When you have an array of data, you would like to perform certain mathematical operations on it

In [23]:
a = np.array( [11, 12, 13, 14]) 
b = np.array( [ 1, 2, 3, 4]) 
c = a - b 
print("===========Subtarctor=============")
print(c)
# Squaring an array 
b = b**2
print(" array Sqaure")
print(b)
# A trigonometric function performed on the array 
print(np.cos(b))

# Conditional operations 
b_cond = b < 2
print("b_condition:\n",b_cond)

===========Subtarctor=============
[10 10 10 10]
 array Sqaure
[ 1  4  9 16]
[ 0.54030231 -0.65364362 -0.91113026 -0.95765948]
b_condition:
 [ True False False False]


In [27]:
# Matrix multiplication
a1 = np.array([[1,2],[1,2]])
a2 = np.array([[2,0],[1,2]])
mul = a1 * a2
print("Simple Multiplication:\n",mul)
dotProduct = np.dot(a1,a2)
print("Dot Product:\n",dotProduct)

Simple Multiplication:
 [[2 0]
 [1 4]]
Dot Product:
 [[4 4]
 [4 4]]


## Indexing and slicing

In [38]:
a1 = np.array([1,2,3,4,5,6,7,8])
bb = a1[0:3]
bb

array([1, 2, 3])

# Shape manipulation

In [45]:
array = np.array([[1,2,3],[5,6,7]])
print("Original Array:\n",array)
flatten =  array.ravel()  # Convert to one dimentinal array
print("Flatten Array:\n",flatten)
flatten.shape = (3,2)
print("Shaped Array:\n",flatten)
print("Transpose\n",flatten.transpose() )

Original Array:
 [[1 2 3]
 [5 6 7]]
Flatten Array:
 [1 2 3 5 6 7]
Shaped Array:
 [[1 2]
 [3 5]
 [6 7]]
Transpose
 [[1 3 6]
 [2 5 7]]


## Inserting and exporting data 
The data is stored in various forms, such as CSV, TSV, databases, and so on. The pandas library makes it convenient to read data from these formats or to export to these formats. 

In [92]:
dataFrame = pd.read_csv('data/studentRecord.csv')

In [51]:
dataFrame.head(5)

Location Code       County  \
0         600000          NaN   
1             15        ESSEX   
2             48       PUTNAM   
3         120501     DELAWARE   
4         660805  WESTCHESTER   

                                           Area Name                 Region  \
0                              NORTHEASTERN NEW YORK  NORTHEASTERN NEW YORK   
1                                              ESSEX  NORTHEASTERN NEW YORK   
2                                             PUTNAM          HUDSON VALLEY   
3  DELAWARE ACADEMY CENTRAL SCHOOL DISTRICT AT DELHI  NORTHEASTERN NEW YORK   
4                VALHALLA UNION FREE SCHOOL DISTRICT          HUDSON VALLEY   

  School Years  Number Overweight  Percent Overweight  Number Obese  \
0    2016-2018            10355.0                16.5       11052.0   
1    2010-2012               78.0                16.3          89.0   
2    2014-2016              697.0                16.3         646.0   
3    2012-2014               38.0                15.3          33.0   
4    2016-2018               85.0                15.7          70.0   

   Percent Obese  Number Overweight or Obese  Percent Overweight or Obese  \
0           17.6                     21407.0                         34.2   
1           18.6                       167.0                         34.9   
2           15.1                      1343.0                         31.4   
3           13.3                        71.0                         28.5   
4           12.9                       155.0                         28.7   

      Grade Level        Area Type    Street Address      City State  \
0  DISTRICT TOTAL           REGION               NaN       NaN   NaN   
1     MIDDLE/HIGH           COUNTY               NaN       NaN   NaN   
2  DISTRICT TOTAL           COUNTY               NaN       NaN   NaN   
3  DISTRICT TOTAL  SCHOOL DISTRICT      2 SHELDON DR     DELHI    NY   
4  DISTRICT TOTAL  SCHOOL DISTRICT  316 COLUMBUS AVE  VALHALLA    NY   

   Zip Code          Location 1  
0       NaN                 NaN  
1       NaN                 NaN  
2       NaN                 NaN  
3   13753.0  (42.2737, -74.916)  
4   10595.0  (41.0927, -73.778)

In [53]:
dataFrame.columns

Index(['Location Code', 'County', 'Area Name', 'Region', 'School Years',
       'Number Overweight', 'Percent Overweight', 'Number Obese',
       'Percent Obese', 'Number Overweight or Obese',
       'Percent Overweight or Obese', 'Grade Level', 'Area Type',
       'Street Address', 'City', 'State', 'Zip Code', 'Location 1'],
      dtype='object')

In [55]:
dataFrame[0:5]['Area Name']

0                                NORTHEASTERN NEW YORK
1                                                ESSEX
2                                               PUTNAM
3    DELAWARE ACADEMY CENTRAL SCHOOL DISTRICT AT DELHI
4                  VALHALLA UNION FREE SCHOOL DISTRICT
Name: Area Name, dtype: object

In [56]:
## Writing Data
data = {
    'Name' : ['Khan','Banana','Kumar','Nazim'],
    'Age' : [25,23,45,67],
    'Salary' : [25000,23000,60000,90000],
    'City' : ['Meerut','Kanpur','Delhi','Punjab'],    
}
dataset = pd.DataFrame(data)

In [58]:
dataset.head()

Name  Age  Salary    City
0    Khan   25   25000  Meerut
1  Banana   23   23000  Kanpur
2   Kumar   45   60000   Delhi
3   Nazim   67   90000  Punjab

In [61]:
dataset.to_csv('data/createdCsv.csv')

In [60]:
dataset.to_excel('data/createdexcel.xls')


In [65]:
dataset.to_json('data/createdjson.json')

## JSON 
To read the data from a JSON file, Python's standard json package can be used

In [66]:
import json
jsonData = open('data/createdjson.json')
data = json.load(jsonData)
jsonData.close()

In [75]:
data

{'Name': {'0': 'Khan', '1': 'Banana', '2': 'Kumar', '3': 'Nazim'},
 'Age': {'0': 25, '1': 23, '2': 45, '3': 67},
 'Salary': {'0': 25000, '1': 23000, '2': 60000, '3': 90000},
 'City': {'0': 'Meerut', '1': 'Kanpur', '2': 'Delhi', '3': 'Punjab'}}

In [70]:
## Using Pandas
dataFrame1 = pd.read_json('data/createdjson.json')

In [76]:
dataFrame1.head()

Name  Age  Salary    City
0    Khan   25   25000  Meerut
1  Banana   23   23000  Kanpur
2   Kumar   45   60000   Delhi
3   Nazim   67   90000  Punjab

In [93]:
## Data cleansing
dataFrame.columns

Index(['Location Code', 'County', 'Area Name', 'Region', 'School Years',
       'Number Overweight', 'Percent Overweight', 'Number Obese',
       'Percent Obese', 'Number Overweight or Obese',
       'Percent Overweight or Obese', 'Grade Level', 'Area Type',
       'Street Address', 'City', 'State', 'Zip Code', 'Location 1'],
      dtype='object')

In [94]:
dataFrame['City'].isnull().sum()

780

In [95]:
dataFrame['City'].isnull().value_counts()

False    8142
True      780
Name: City, dtype: int64

In [96]:
dataFrame.isnull().sum()

Location Code                    0
County                          84
Area Name                        0
Region                           0
School Years                     0
Number Overweight              574
Percent Overweight             574
Number Obese                   570
Percent Obese                  569
Number Overweight or Obese     716
Percent Overweight or Obese    716
Grade Level                      0
Area Type                        0
Street Address                 780
City                           780
State                          799
Zip Code                       780
Location 1                     781
dtype: int64

In [99]:
dataFrame['City'].dropna(how = 'any', inplace = True)

In [105]:
dataFrame['City'].isnull().value_counts()

False    8142
Name: City, dtype: int64

# Filling the missing data 

In [109]:
dataFrame.isnull().sum()

Location Code                    0
County                          84
Area Name                        0
Region                           0
School Years                     0
Number Overweight              574
Percent Overweight             574
Number Obese                   570
Percent Obese                  569
Number Overweight or Obese     716
Percent Overweight or Obese    716
Grade Level                      0
Area Type                        0
Street Address                 780
City                           780
State                          799
Zip Code                       780
Location 1                     781
dtype: int64

In [111]:
dataFrame['Number Overweight'].isnull().value_counts()

False    8348
True      574
Name: Number Overweight, dtype: int64

In [114]:
dataFrame['Number Overweight'].fillna(dataFrame['Number Overweight'].mean(),inplace = True)
 
 

In [116]:
dataFrame['Number Overweight'].isnull().value_counts()

False    8922
Name: Number Overweight, dtype: int64

In [150]:
import math
data1 = {
    'Name' : ['Khan','Banana','Kumar','Nazim'],
    'Age' : [25,23,45,67],
    'Salary' : [25000,23000,math.nan,90000],
    'City' : ['Meerut','Kanpur',math.nan,'Punjab'],    
}
dataset1 = pd.DataFrame(data1)

In [151]:
dataset1.head()

Name  Age   Salary    City
0    Khan   25  25000.0  Meerut
1  Banana   23  23000.0  Kanpur
2   Kumar   45      NaN     NaN
3   Nazim   67  90000.0  Punjab

In [154]:
#dataset1['Salary'].fillna(method = 'backfill', inplace = True ) # method 'backfill', 'bfill', 'pad', 'ffill',
dataset1['City'].fillna(method = 'backfill', inplace = True ) # method 'backfill', 'bfill', 'pad', 'ffill',

In [156]:
dataset1.head()

Name  Age   Salary    City
0    Khan   25  25000.0  Meerut
1  Banana   23  23000.0  Kanpur
2   Kumar   45  90000.0  Punjab
3   Nazim   67  90000.0  Punjab

In [162]:
dataset1['City'].str[0:3]

0    Mee
1    Kan
2    Pun
3    Pun
Name: City, dtype: object

## Merging Data

In [165]:
dataset1[['Name','Salary']][0:3]

Name   Salary
0    Khan  25000.0
1  Banana  23000.0
2   Kumar  90000.0

In [167]:
d1 = dataset1[['Name','Salary']][0:2]
d1

Name   Salary
0    Khan  25000.0
1  Banana  23000.0

In [169]:
d2 = dataset1[['Name','Salary']][2:4]
d2

Name   Salary
2  Kumar  90000.0
3  Nazim  90000.0

In [176]:
concatData = pd.concat([d2,d1])

In [173]:
concatData

Name   Salary
2   Kumar  90000.0
3   Nazim  90000.0
0    Khan  25000.0
1  Banana  23000.0

In [178]:
## The combined pieces can be identified by assigning a key
concatData1 = pd.concat([d2,d1], keys = ['p1','p2'])
concatData1

Name   Salary
p1 2   Kumar  90000.0
   3   Nazim  90000.0
p2 0    Khan  25000.0
   1  Banana  23000.0

In [184]:
concatData1.loc['p1']

Name   Salary
2  Kumar  90000.0
3  Nazim  90000.0

In [196]:
## Concate data frame
concatData = pd.concat([df1,df2])
concatData

id Feature1 Feature2
0  1        A        B
1  2        C        D
2  3        E        F
3  4        G        H
4  5        I        J
0  1        K        L
1  2        M        N
2  6        O        P
3  7        Q        R
4  8        S        T

ou can notice that the two DataFrames df1 and df2 are now concatenated into a single DataFrame df_row along the row. However, the row labels seem to be wrong
# ignore_index
If you want the row labels to adjust automatically according to the join, you will have to set the argument ignore_index as True while calling the concat() function

In [198]:
concateData_reindex = pd.concat([df1,df2],ignore_index = True ) # It will create fresh index
concateData_reindex

id Feature1 Feature2
0  1        A        B
1  2        C        D
2  3        E        F
3  4        G        H
4  5        I        J
5  1        K        L
6  2        M        N
7  6        O        P
8  7        Q        R
9  8        S        T